### ISSUE TITLE
KeyError: 'device' when adding my new laptop

### ISSUE THREAD

**Issue by mhoogenbosch** [hass-agent/HASS.Agent-Integration#5]
I'm trying to add my new laptop to HA by utilizing this integration. 

Unfortunately, I'm getting the following error presented:

```
Logger: homeassistant.config_entries
Bron: config_entries.py:586
Eerst voorgekomen: 09:16:17 (5 gebeurtenissen)
Laatst gelogd: 09:51:15

Error setting up entry DESKTOP-2Z5DV73-HassAgent for hass_agent
Error setting up entry G10LaptopHassAgent for hass_agent
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hass_agent/__init__.py", line 135, in async_setup_entry
    _logger.debug("setting up device from config entry: %s [%s]", entry.data["device"]["name"], entry.unique_id)
                                                                  ~~~~~~~~~~^^^^^^^^^^
KeyError: 'device'
```

The first setting up entry, starting with DESKTOP was the default value (added HassAgent for better visibility inside). The second entry starting with G10 is a new name I picked because of testing, but the error is the same.

The port is configured as 5115, but it happens with all configured ports. 

HassAgent is beta2 of version 2.1.0. HA is 2024.7.2.

**Comment by mhoogenbosch** [comment]
I just don't know where my error is at.

I opened this bug because I thought I was merely the integration which was acting up.

But now I'm starting to suspect the Hass.Agent itself. On my old laptop, called 'martijnlaptop' it immediately gets discovered by MQTT and thus the integration. When removing Hass.Agent device, and restart of HA, it comes back with the message new devices have been discovered.

With my new laptop this doesn't happen. When I rename DESKTOP-2Z5DV73 to any other device name, it just stops pushing changes to HA. The changes do get reflected with MQTT but it doesn't get detected by HA.

With extended logging enabled the only error is this:

```
2024-07-15 21:14:18.432 +02:00 [FTL] [PROGRAM] FirstChanceException: Unable to cast COM object of type 'System.__ComObject' to interface type 'NAudio.CoreAudioApi.Interfaces.IMMDevice'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{D666063F-1587-4E43-81F1-B948E807363F}' failed due to the following error: Interface wordt niet ondersteund (0x80004002 (E_NOINTERFACE)).
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'NAudio.CoreAudioApi.Interfaces.IMMDevice'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{D666063F-1587-4E43-81F1-B948E807363F}' failed due to the following error: Interface wordt niet ondersteund (0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at NAudio.CoreAudioApi.Interfaces.IMMDevice.GetState(DeviceState& state)
   at NAudio.CoreAudioApi.MMDevice.get_State()
   at HASS.Agent.Shared.Managers.Audio.AudioManager.<>c.<GetDevices>b__18_0(InternalAudioDevice d) in D:\a\HASS.Agent\HASS.Agent\src\HASS.Agent\HASS.Agent.Shared\Managers\Audio\AudioManager.cs:line 225
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at HASS.Agent.Shared.Managers.Audio.AudioManager.GetDevices() in D:\a\HASS.Agent\HASS.Agent\src\HASS.Agent\HASS.Agent.Shared\Managers\Audio\AudioManager.cs:line 225
```

[[2024-07-15] HASS.Agent_20240715.log](https://github.com/user-attachments/files/16239304/2024-07-15.HASS.Agent_20240715.log)

Attached logfile, but maybe I should open this with the Hass.Agent github instead?

**Comment by BC48329** [comment]
I'm having the same issue

No new devices being discovered (specifically media players)

Manual MQTT sensors are discovered

I tried two different PCs with the same results

**Comment by amadeo-alex** [comment]
Hello, apologies for the delay in response.

As an introduction statement: the integration requires a full rework - I'm working on this as the coming-going issues like "new device not being discovered", "device appearing as discovered despite already being configured" etc. are the result of the integration being written back in the day by original team and then "maintained" to the best of efforts.
The target is to rewrite it from scratch.

@mhoogenbosch I see that you've mentioned ports, are you using local API?
As a rule of thumb the better way is to go with the auto-discovery as the local API is in "life-support" stage (although looking at the issues I understand why people still use local API)

As a first step I'd like to ask both of you to:
1. make sure if you're using the forked version of integration - https://github.com/hass-agent/HASS.Agent-Integration/issues/2
2. remove all discovered/configured HASS.Agent devices (in the integration details page)
3. close all HASS.Agent instances that might be running (including satellite service)
4. in MQTT-Explorer, remove all topics/messages under "hass.agent/devices"
5. restart Home Assistant
6. start all HASS.Agent instances
7. restart Home Assistant
8. the devices should appear as discovered - configure them and optionally restart Home Assistant again

Just to be clear - the restarts are required due to integration issues and not Home Assistant issues.

**Comment by lutin-malin** [comment]
for anyone interested, sequence mentionned above by @amadeo-alex works well for me  !

thanks for the time invested on this agent to the team
